sudo: required
dist: trusty
language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
matrix:
  include:
  - script:
    - npm test
    - bash <(curl -s https://codecov.io/bash)
  - script: bash ./surge_deploy_test.sh
#deploy:
#  provider: heroku
#  api_key:
#    secure: PFudHkB9SkNZQ+qJkgx0xMh0g6xemdN0ZLne5BeABfUfu+8swDU5TxNU1xbcs6IWDKassmPmnJc5fiKGp8sCRukdLyQi3ap/khMM/+thKuDu4EVEnJCBGpSwaCTP+r2zNRuwvlswcAyj2WyeDggkW3HHIAPYhz9WBuciERojySVTBRAoEVwRzjxizV2k9t7UCVHpdASF+yR+oVYLYqnPi8wToIGmtVhWIXMIwE/hU92fgQbHkWzGKdYLba/P6wmsVyrGxJVrVBlLjxMPF+KIc8z9uML2p97+u9qqGW65nM3LwYl1otXbDeQBHtA5TPB9x+LmksifRvJgfKxj46gcCkwC5AaK/vszni1eCaHrfEY30TxD7/dDEvstsdRpO6aNkIyk7Y2M3N8rgx+PH17ZWKgmtfOjipck3dEEHE+XXBGRCdCZIgVpbfM39mNjtq+6NxnQMn2+z/uZAz2+yLRGm/MA9Gyu/3tCgS5yaLpuHiuD9fn4brk79oYUHFgyUGdvw3/db1Gv0+9tz3mdkIa9xqIKfiJiA4U0xVpv8VfWdMZ1xeQCr6KHDGuiwnOqOxwiqlrwQUq6g8ynVZ5MNv9hMVlXIfCd/1YyQBlRW1aubcmu+X72o+MJQuX2Y4jbH2Xrs+hQsYVnz/wQTXD1hscagwPSDcQg6rhGyFBz/zl8g40=
#  app: susi-build-her
#  on:
#    repo: jayasanka-sack/susi.ai
